### ISSUE TITLE
Unicode build on windows ?

### ISSUE THREAD

**Issue by Jeromnimo** [ladislav-zezula/CascLib#115]
Hi Ladislav, hope you're doing well.
I am currently working on switching WoW Model Viewer to unicode build (it is still using multi byte for years, due to old code base) and I was about to push a pull request to allow using an argument when calling CMake to force unicode build for casclib.

Do you think it is fine to alsways force it for windows builds  (several libraries are already doing it) or do you prefer keeping it as optional ?

If anyone is using casclib under windows, your feedbacks are welcome as well.

**Comment by ladislav-zezula** [comment]
CascLib was designed to be able to use UNICODE file names (i.e. CascOpenStorage accepts const TCHAR * as folder name). However, the ANSI stuff, that is presents in listfiles/ROOT) is forced to be ANSI.

**Comment by Jeromnimo** [comment]
Yes, and my point is only at project level in Visual Studio.
To be clear, it's only a matter of adding add_definitions("-DUNICODE -D-UNICODE") in CMakeLists.txt
Question is : shall this proejct setting be forced or let optional through a CMake argument ?

**Comment by ladislav-zezula** [comment]
Ideally, it would be optional as a build switch.

**Comment by Jeromnimo** [comment]
Ok, I will then add it as a cmake option, thanks Ladislav

**Comment by herrvigg** [comment]
Just by curiosity are you using Visual Studio with CMake? Which Visual Studio? Why not using the project files?

Ah, the UNICODE joy on Windows and the TCHAR horror...
I struggled also a lot with it and the code pages can become a nightmare. It's such a non-sense to still have wide chars for UTF-16 when everyone else in the world (or almost) uses UTF-8 on 1-byte char. So many people (Windows developers) still think that Unicode implies wide char but it's not the case. This is a must-read for any developer dealing with this: http://utf8everywhere.org/
The sad thing is that UTF-8 is still not supported with the ANSI Win API and because of their huge legacy i doubt it ever will :-(

For CascLib it also took me a bit of time to understand but finally i think i got it: only the internal CASC structure is ANSI and the interface to CascLib is mutable at compile-time through TCHAR (sic).

**Comment by Jeromnimo** [comment]
I'm using cmake tool chain to generate VIsual Studio solution (today, I'm using VS2013, but I have engaged - unicode is one - several updates to move to VS2017)
casclib usage is visible here : https://bitbucket.org/wowmodelviewer/wowmodelviewer/src/6efed82d6848b86dd8bb2e978b51f30138aa8471/src/casclib/CMakeLists.txt?at=default&fileviewer=file-view-default

**Comment by ladislav-zezula** [comment]
@herrvigg: Using Visual Studio 2008, 2015 and 2017. No, I don't use CMakeLists.txt, as this seems terribly complicated for anyone not used to it.
