### ISSUE TITLE
Battle for Azeroth Patch 8.1.5. cinematics extracting

### ISSUE THREAD

**Issue by Streetx2k7** [ladislav-zezula/CascLib#132]
Hi guys!

Can you help me with new 8.1.5. BfA patch?

I want to extracting the following cinematic file:
interface/cinematics/bfa_815_dpr_1920.avi

Thanks for the help!

**Comment by ladislav-zezula** [comment]
Any chance of describing what does not work? Error message perhaps?

**Comment by Streetx2k7** [comment]
Failed to extract the file "interface/cinematics/bfa_815_dpr_1920.avi".
The specified file is encrypted and the user does not have the ability to decrypt it.

**Comment by ladislav-zezula** [comment]
This is because when Blizzard releases a new stuff, it is encrypted inside the data files. Decryption keys are released when the stuff is supposed to be public.

Unlike MPQs, where the encryption was really weak, Casc data are encrypted by Salsa, and thus there is no real chance to brute-force the key.
