### ISSUE TITLE
Sharing violation

### ISSUE THREAD

**Issue by Suicidal-Insanity** [ladislav-zezula/CascLib#158]
FYI, adding FILE_SHARE_WRITE | FILE_SHARE_DELETE to the CreateFile call in BaseFile_Open allows the CASC to be opened while a game is running. The files with sharing issues appear to be read immediately, but I don't know enough about the CASC structure to know whether this will cause issues down the line, so I just want to mention it, not explicitly push a change.

**Comment by ladislav-zezula** [comment]
Hi,

Yes, it does allow. The FILE_SHARE_WRITE was added quite recently. People complained that when they run Battle.net app while the storage is open by CascView, the Battle.net App triggers data repair.

See here:
https://github.com/ladislav-zezula/CascLib/issues/131

Also, someone complained that they cannot open the storage while the WoW is running.
https://github.com/ladislav-zezula/CascLib/issues/54

Technically, it is wrong to allow the storage to be open while the game client is also running. It can trigger all kind of mayhem, like files being updated on the fly. However, due to human nature ("I am lazy / busy to keep closing the game every time when I want to read game data"), this seems to be the least worst option.
