### ISSUE TITLE
CascReadFile fails with ERROR_BAD_FORMAT

### ISSUE THREAD

**Issue by Naros** [ladislav-zezula/CascLib#172]
I am attempting to load a file using the master branch as of commit e4f96bd8.  When `CascOpenFile` is called, the library successfully opens the file; however when I first begin to read the file, the call to `CascReadFile` returns with an `ERROR_BAD_FORMAT` code.

The file attempting to accessed is: `world/maps/kalimdor/kalimdor_25_9.adt`
The file data id is: `783335`

This same problem seems to persist when loading terrain data as it relates to Kalimdor, Eastern Kingdoms, Pandaria, and Dreanor; however does not seem to be a problem for maps such as Northrend, Zandalar, or Kultiras.

From my quick debugging related to the above file, it seems the problem happens during the call to `ParseBlteHeader` in `CascReadFile.cpp` at line 160 where the BLTE_HEADER_SIGNATURE is verified.  The resolved signature is 0xAA23F16E which does not match the expected 0x45544c42 magic sequence.

It should be worth noting that my installation has both retail and classic wow.

**Comment by ladislav-zezula** [comment]
This is gonna be a problem to debug. I checked on my installation of WoW and it works (note than it always work on my PC hehe).

I opened the latest build of WoW in CascView. Here's the file properties:
![extracted-file](https://user-images.githubusercontent.com/3244359/69126673-005bfa00-0aa9-11ea-8ff0-53d0c7a50261.png)
As you can see the Content Key for the file is `6683083d269c07e9a81384340a911902`, which matches the MD5 of the extracted file. That means the file is perfectly correct and also perfectly correctly extracted.

As for your error. First of all, please, get the newest build of CascView. I did quite a few improvements and bugfixes there. Second, run your BNET Client and do "Scan and Repair". Due to its size and nature, I see various storage errors very often. Then, try to open that file again and tell me its MD5.

**Comment by Naros** [comment]
Performing the "Scan and Repair" resolved the problem.  One last question; what care (if any) must one take when using CascLib to read files from multiple threads?

**Comment by ladislav-zezula** [comment]
You need to synchronize `CascOpenFile` and `CascGetFileInfo`.

Given that I came accross multithread issue myself, i'll add the support directly to CascLib.

**Comment by ladislav-zezula** [comment]
Since commit f9fc9a255afdef4efe5c229cff6b0f7ba806ffdf, it should be thread-safe as long as you open the storage from single thread and then open/read files from multiple threads.
