### ISSUE TITLE
CascView issue with Patch 9.1 PTR

### ISSUE THREAD

**Issue by WainPetopia** [ladislav-zezula/CascLib#199]
Using the latest CascView build from zezula.net, and the latest Listfile from wow.tools, I can open the retail version of WoW fine, but the PTR version gives a strange file listing that suggests it's not finding the correct data directory. It was working a few builds ago, and I'm unsure what has changed. I can try to find out more later, but for now I just wanted to at least report the issue. A screenshot of what CascView's file tree looks like with 9.1 is attached.

I should mention that WoW Model Viewer has also stopped loading the 9.1 PTR version, and the error in its log is that it's unable to set the locale to enUS (but it works fine if I try to load retail).

![CascViewError9 1](https://user-images.githubusercontent.com/25504585/117839658-c4c97700-b2be-11eb-8020-a1dda7309d43.png)

**Comment by ladislav-zezula** [comment]
Re: [ladislav-zezula/CascLib] CascView issue with Patch 9.1 PTR (#199)



Meh, this morning I uninstalled PTR from my PC
and thought I'll save some disk space ...

I'll install the PTR back and try to figure out.

L.





Using the latest CascView build from zezula.net, and the latest Listfile from wow.tools, I can open the retail version of WoW fine, but the PTR version gives a strange file listing that suggests it's not finding the correct directory. It was working a few builds ago, and I'm unsure what has changed. I can try to find out more later, but for now I just wanted to at least report the issue. A screenshot of what CascView's file tree looks like with 9.1 is (hopefully) attached below.
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.





--
S pozdravem,
 Ladislav Zezula
***@***.***

**Comment by WainPetopia** [comment]
Thanks heaps for your quick fix! :)
