### ISSUE TITLE
CASCLib fails to open modern online storage

### ISSUE THREAD

**Issue by skarnproject** [ladislav-zezula/CascLib#229]
BAD_FORMAT error is returned on attempt to open online storages (did not test local storages, maybe these ones too). The issue is most likely related to TVFS.

CascView.exe, which I believe is based on this lib, is also not able to connect to these.

**Comment by ladislav-zezula** [comment]
Which storage are you referring to? Which game/build?

**Comment by skarnproject** [comment]
World of Warcraft, online storage (Blizzard), pretty much all products e.g. wow / wowt / wow_classic

**Comment by ladislav-zezula** [comment]
Interesting. This is what I get:
![obrazek](https://user-images.githubusercontent.com/3244359/216613763-6592ba9e-e3c1-471f-be5a-d5a608d731ea.png)

**Comment by skarnproject** [comment]
Russia

**Comment by Talv** [comment]
I believe this is a WINE issue. OP is running the app on Linux through a WINE compatibility layer.

I've been running into the same problem, but I never really attempted to look after solution, as I've always resorted to intermediate workarounds (such as launching Windows VM in the background).

But recently I've actually noticed it does work, if one opens a local CASC storage first, and then once it's done the app sort of *wakeups*. And since this moment the connectivity is enabled, and by that also the ability to connect with remote storages. The app behaves as it didn't have the internet connection at all - or assumed that it didn't have one - because it literally haven't spotted any attempt of making the connection (I haven't noticed anything being sent through the system net sockets).

Anyway, so while this works, the process must be repeated after each restart of the application. And obviously, one needs to have some Blizzard game installed beforehand.

I've also looked at default WINE logs from this session, but there wasn't anything obvious in there. With the exception of a call to `wininet.dll`@`InternetCheckConnectionW`. However, this call was mode AFTER I've opened the local storage, so it's weird. I think there must be something in the app logic that contributes to this behavior, or the port of a `wininet.dll` that's present in WINE is malfunctioning in some way.

Unfortunately that's all the info I'm able to give, because I don't have the WINE configured in a way that would allow me to sniff the communications between the `.dll` in some elegant way.

**Comment by Talv** [comment]
> This is a screenshot from latest CASCView.exe 64 bit. But BAD_FORMAT error is returned on using the bare CascLib as well, which makes this issue more relevant to the lib, than the tool.

I'm using the the lib for quite some time and never had any major issues - neither on ony Windows, nor Linux. But I only play few Blizzard games (and that doesn't include WoW). 

Also in both cases I run it natively, and have compiled manually from sources.. which are at least couple months old by now.

**Comment by ladislav-zezula** [comment]
@Talv: Thanks to your excellent problem description, I was able to find the root cause. Even tho CascLib [calls](https://github.com/ladislav-zezula/CascLib/blob/1456569bb09a5cbac0b6dfa70205c4930e68194d/src/common/Sockets.cpp#L178) `WSAStartup`, if needed, this does not work under WINE. I added an explicit call to WSAStartup to WinMain and it now works OK.

[Download](http://zezula.net/en/casc/main.html) the latest CascView from my website.

**Comment by Talv** [comment]
Great to hear you got to the bottom of this!

I've just downloaded latest version and can confirm that the issue is gone on my end too. Thanks!
