### ISSUE TITLE
Windows: Initialization fails because CascLib is looking for .agent.db

### ISSUE THREAD

**Issue by robpaveza** [ladislav-zezula/CascLib#26]
On my Windows machine, games are located as such:

* c:\Program Files (x86)\Battle.net\ <-- This is where .agent.db lives
* c:\Program Files (x86)\Heroes of the Storm\ <-- .build.info lives here
* c:\Program Files (x86)\World of Warcraft\ <-- .build.info lives here

Games are fully patched.  

Even the comments of `InitializeCascDirectories` says "The root directory is the one where `.build.info` is", but `CheckGameDirectory()` looks for `.agent.db`.  If I modify `InitializeCascDirectories` to check the parent of the current directory for `.build.info` instead, it works.

**Comment by ladislav-zezula** [comment]
The problem is more complcated than that. The Agent.db is searched because CascLib searches for the data subdirectory there. My plan was that caller of CascOpenStorage could use any directory within the game
- The game directory itself
- Any subdirectory
To see where the CASC data are actually located, the library searches for ".agent.db" to find "data_dir" there. That is then used as a subdirectory where the data files are searched.

**Comment by robpaveza** [comment]
I do not find .agent.db within my game directories at all.

**Comment by ladislav-zezula** [comment]
Hmm, that sucks. I'll have to rethink the searching then.
