### ISSUE TITLE
minor issue: missing VS15 projects

### ISSUE THREAD

**Issue by herrvigg** [ladislav-zezula/CascLib#68]
hello,
just a minor issue with the VS15 solution. The DLL and test projects are missing in the solution package because it references the `.vcxproj` for all projects but only the `.vcproj` exist for those last 2 projects. The main lib project is fine. Here are the concerned files:

- CascLib_vs15.sln : ok
- CascLib_vs15.vcxproj : ok
- CascLib_vs15_dll.vcproj -> CascLib_vs15_dll.vcxproj
- CascLib_vs15_test.vcproj -> CascLib_vs15_test.vcxproj

As i use VS17 i prefer not to change these files so i let someone having VS15 correct them to keep a compatible version in the git repo. Btw the upgrade VS15->VS17 is fine and smoother than VS08->VS17.

Other minor point, when building the CascLib_Test i had this linker error: `module unsafe for SAFESEH image.`. I fixed it like this:
CascLib_Test properties > linker > Image Has Safe Exception Handler -> No (/SAFESEH:NO)
Maybe this should be set in the CascLib_test project as well.

When this is fixed in the repo, i will update my local stuff and i can make a pull request for the VS17 files if you are interested.

**Comment by ladislav-zezula** [comment]
Missing files fixed. As for the SAFESEH thing, this is an usual problem when upgrading VS2008 files to VS 2015. Needs to be manually turned off for X64 builds and for all DEBUG builds. This was already done in the _vs15.vcxproj files, but since I didn't add them to repo, this problem arrived.

If you want to make pull request for VS 2017, feel free to do so. Please, name the files using the same scheme like it is now, e.g. CascLib_vs17*.vcxproj
